name: Deploy documentation

on:
  push:
    branches:
      - master

jobs:
  pre_deploy:
    name: Deploy to GitHub Pages
    runs-on: ubuntu-latest
    outputs:
      docs_changed: ${{ steps.docs-files.outputs.any_changed }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Get changed files in the docs folder
        id: docs-files
        uses: tj-actions/changed-files@v31
        with:
          files: docs/**

  deploy:
    runs-on: ubuntu-latest
    needs: [pre_deploy]
    if: needs.pre_deploy.outputs.docs_changed == 'true'
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: 'https://registry.npmjs.org'
      - name: Install dependencies ⏳
        working-directory: ./docs
        run: npm ci
      - name: Build 🔧
        working-directory: ./docs
        run: npm run build
      - name: Deploy docs to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/build
